#!/usr/bin/env python

import os
import shutil
import sys
from diffusers import DiffusionPipeline
import torch

# append project directory to path so predict.py can be imported
sys.path.append('.')

from predict import MODEL_NAME, MODEL_CACHE

if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)

# get token from argument
YOUR_HF_TOKEN = sys.argv[1]

model = DiffusionPipeline.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
    use_auth_token=YOUR_HF_TOKEN,
    cache_dir=MODEL_CACHE,
)